name: Test, Build, and Deploy | Modul 01 = Lab2.2 Senior Project

on:
  push:
    branches: [main]

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          node-version: '20.x' 
      - name: Testing Build pre-Deploy
        uses: actions/setup-node@v2
        with:
          node-version: '20.x' 
          cache: 'npm'
      - run: npm i
      - run: npm run build
